s3_bucket: <%= ENV["S3_BUCKET"] %>
aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
aws_region: <%= ENV["AWS_REGION"] %>
twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
tiwtter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>