s3_bucket: <%= ENV["AWS_S3_BUCKET_NAME"] %>
aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
aws_region: <%= ENV["AWS_REGION"] %>
author:
  email: <%= ENV["ADMIN_EMAIL"] %>
  password: <%= ENV["ADMIN_PASSWORD"] %>
